=head1 NAME

Blosxom::Header::Fast - Modify $blosxom::header directly

=head1 SYNOPSIS

  no Blosxom::Header;

  $blosxom::header->{-status} = '304 Not Modified'; # set

  my $value   = $blosxom::header->{-status};                # get
  my $bool    = exists $blosxom::header->{-etag};           # exists
  my $deleted = delete $blosxom::header->{-content_length}; # delete

  %{ $blosxom::header } = (); # clear

=head1 DESCRIPTION

No need to load L<Blosxom::Header>. Normalized keys are:

  'Foo'  # not normalized
  '-foo' # normalized

  'Foo-Bar'  # not normalized
  '-foo_bar' # normalized

  '-content_type' # not normalized
  '-type'         # normalized

  '-set_cookie' # not normalized
  '-cookie'     # normalized

  '-cookies' # not normalized
  '-cookie'  # normalized

The above way is compatible with L<Blosxom::Header>.

=head1 SEE ALSO

L<Blosxom::Header>

=head1 AUTHOR

Ryo Anazawa (anazawa@cpan.org)

=head1 LICENSE AND COPYRIGHT

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.

=cut
