---
abstract: 'Object representing CGI response headers'
author:
  - 'Ryo Anazawa (anazawa@cpan.org)'
build_requires:
  CGI: 3.49
  ExtUtils::MakeMaker: 6.59
  Test::Base: 0.60
  Test::Exception: 0.31
  Test::More: 0.98
  Test::Pod: 1.45
  Test::Warn: 0.24
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Blosxom::Header
name: Blosxom-Header
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CGI::Cookie: 1.29
  CGI::Util: 3.53
  Carp: 1.10
  Exporter: 5.63
  HTTP::Date: 6.02
  HTTP::Status: 6.03
  List::Util: 1.19
  Scalar::Util: 1.19
  overload: 1.06
  perl: 5.8.9
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/anazawa/p5-Blosxom-Header
version: 0.06001
